name: Update Secret HTML

on: [push]

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace placeholder with secret HTML
      run: |
        sed -i "s|{{ACCESS_KEY_HTML}}|${{ secrets.ACCESS_KEY_HTML }}|g" index.html

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add index.html
        git commit -m 'Update access key HTML'
        git push
